project_id = "cjnukzmjenfvuopooumb"

[functions.create-chain]
verify_jwt = false

[functions.expire-chains]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.send-a-ment]
verify_jwt = false

[functions.check-expiring-chains]
verify_jwt = false

[functions.send-completed-email]
verify_jwt = false

[functions.send-milestone-email]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false